# Generated by Django 5.2.4 on 2025-08-05 18:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategorie Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('order', models.IntegerField(default=0, verbose_name='Reihenfolge')),
            ],
            options={
                'verbose_name': 'Projektkategorie',
                'verbose_name_plural': 'Projektkategorien',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Projekttitel')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL-Slug')),
                ('description', models.TextField(verbose_name='Beschreibung')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='Kurzbeschreibung')),
                ('client', models.CharField(blank=True, max_length=200, verbose_name='Kunde')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Standort')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='Fertigstellungsdatum')),
                ('main_image', models.ImageField(upload_to='projects/main/', verbose_name='Hauptbild')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Hervorgehoben')),
                ('order', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.projectcategory', verbose_name='Kategorie')),
            ],
            options={
                'verbose_name': 'Projekt',
                'verbose_name_plural': 'Projekte',
                'ordering': ['-is_featured', 'order', '-completion_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/', verbose_name='Bild')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Bildunterschrift')),
                ('order', models.IntegerField(default=0, verbose_name='Reihenfolge')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='projects.project', verbose_name='Projekt')),
            ],
            options={
                'verbose_name': 'Projektbild',
                'verbose_name_plural': 'Projektbilder',
                'ordering': ['order'],
            },
        ),
    ]
