# Generated by Django 5.2.4 on 2025-08-05 18:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Firma')),
                ('subject', models.CharField(max_length=200, verbose_name='Betreff')),
                ('message', models.TextField(verbose_name='Nachricht')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Eingegangen am')),
                ('is_read', models.BooleanField(default=False, verbose_name='Gelesen')),
                ('is_responded', models.BooleanField(default=False, verbose_name='Beantwortet')),
            ],
            options={
                'verbose_name': 'Kontaktnachricht',
                'verbose_name_plural': 'Kontaktnachrichten',
                'ordering': ['-created_at'],
            },
        ),
    ]
